apiVersion: v1
kind: Service
metadata:
  name: hubapi
  namespace: helloafzal3  
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: azure-vote-front