kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data1"