kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"