kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: appdb
  labels:
    app: postgres
spec:
  storageClassName: manualapp
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi