kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volumeapp
spec:
  storageClassName: manualapp
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"